# Generated by Django 6.0.1 on 2026-01-27 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_hotel_ville'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='ville',
        ),
    ]
