# Generated by Django 6.0.1 on 2026-01-27 13:18

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_remove_hotel_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='prix',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='ville',
            field=models.CharField(default='Dakar', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='adresse',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='nom',
            field=models.CharField(max_length=100),
        ),
    ]
